# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto3_field_presence.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "TestEnum",
    "InnerTest",
    "Test",
)

import datetime
from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


class TestEnum(betterproto2.Enum):
    A = 0

    B = 1


@dataclass(eq=False, repr=False)
class InnerTest(betterproto2.Message):
    test: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """


    Oneofs:
        - _test1:
        - _test2:
        - _test3:
        - _test4:
        - _test5:
        - _test6:
        - _test7:
        - _test8:
        - _test9:
    """

    test1: "Optional[int]" = betterproto2.field(1, betterproto2.TYPE_UINT32, optional=True)
    test2: "Optional[bool]" = betterproto2.field(2, betterproto2.TYPE_BOOL, optional=True)
    test3: "Optional[str]" = betterproto2.field(3, betterproto2.TYPE_STRING, optional=True)
    test4: "Optional[bytes]" = betterproto2.field(4, betterproto2.TYPE_BYTES, optional=True)
    test5: "Optional[InnerTest]" = betterproto2.field(5, betterproto2.TYPE_MESSAGE, optional=True)
    test6: "Optional[TestEnum]" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, optional=True, default_factory=lambda: TestEnum.try_value(0)
    )
    test7: "Optional[int]" = betterproto2.field(7, betterproto2.TYPE_UINT64, optional=True)
    test8: "Optional[float]" = betterproto2.field(8, betterproto2.TYPE_FLOAT, optional=True)
    test9: "Optional[datetime.datetime]" = betterproto2.field(9, betterproto2.TYPE_MESSAGE, optional=True)
