# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto3_field_presence_oneof.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "InnerNested",
    "Nested",
    "Test",
    "WithOptional",
)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class InnerNested(betterproto2.Message):
    a: "bool | None" = betterproto2.field(1, betterproto2.TYPE_BOOL, optional=True)


default_message_pool.register_message("proto3_field_presence_oneof", "InnerNested", InnerNested)


@dataclass(eq=False, repr=False)
class Nested(betterproto2.Message):
    inner: "InnerNested | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("proto3_field_presence_oneof", "Nested", Nested)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """


    Oneofs:
        - kind:
    """

    nested: "Nested | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True, group="kind")

    with_optional: "WithOptional | None" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True, group="kind")


default_message_pool.register_message("proto3_field_presence_oneof", "Test", Test)


@dataclass(eq=False, repr=False)
class WithOptional(betterproto2.Message):
    b: "bool | None" = betterproto2.field(2, betterproto2.TYPE_BOOL, optional=True)


default_message_pool.register_message("proto3_field_presence_oneof", "WithOptional", WithOptional)
