# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto3_field_presence_oneof.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "InnerNested",
    "Nested",
    "Test",
    "WithOptional",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False)
class InnerNested(betterproto2.Message):
    """


    Oneofs:
        - _a:
    """

    a: "Optional[bool]" = betterproto2.field(1, betterproto2.TYPE_BOOL, optional=True)


@dataclass(eq=False, repr=False)
class Nested(betterproto2.Message):
    inner: "Optional[InnerNested]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """


    Oneofs:
        - kind:
    """

    nested: "Optional[Nested]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True, group="kind")
    with_optional: "Optional[WithOptional]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="kind"
    )


@dataclass(eq=False, repr=False)
class WithOptional(betterproto2.Message):
    """


    Oneofs:
        - _b:
    """

    b: "Optional[bool]" = betterproto2.field(2, betterproto2.TYPE_BOOL, optional=True)
