# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: messages.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "DoThingRequest",
    "DoThingResponse",
    "GetThingRequest",
    "GetThingResponse",
)

import datetime
from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    List,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False)
class DoThingRequest(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    comments: "List[str]" = betterproto2.field(2, betterproto2.TYPE_STRING, repeated=True)
    """
    use `repeated` so we can check if `List` is correctly imported
    """
    when: "Optional[datetime.datetime]" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True)
    """
    use google types `timestamp` and `duration` so we can check
    if everything from `datetime` is correctly imported
    """
    duration: "Optional[datetime.timedelta]" = betterproto2.field(4, betterproto2.TYPE_MESSAGE, optional=True)


@dataclass(eq=False, repr=False)
class DoThingResponse(betterproto2.Message):
    names: "List[str]" = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=True)


@dataclass(eq=False, repr=False)
class GetThingRequest(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class GetThingResponse(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    version: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
