# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: package_message.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("PackageMessage",)

from dataclasses import dataclass

import betterproto2

from ...message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class PackageMessage(betterproto2.Message):
    c: "childpackage.ChildMessage | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("import_child_package_from_package.package", "PackageMessage", PackageMessage)


from . import childpackage
