# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: package_message.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("PackageMessage",)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class PackageMessage(betterproto2.Message):
    c: "Optional[childpackage.ChildMessage]" = betterproto2.message_field(1, optional=True)


from . import childpackage
