# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: child.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Message",)

from dataclasses import dataclass

import betterproto2

from ...message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class Message(betterproto2.Message):
    pass


default_message_pool.register_message("import_child_package_from_root.childpackage", "Message", Message)
