# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: package.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Weapon",)


import betterproto2
from pydantic.dataclasses import dataclass

from ...message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Weapon(betterproto2.Message):
    pass


default_message_pool.register_message("nested2.equipment", "Weapon", Weapon)
