# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: googletypes_response_embedded.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Input",
    "Output",
    "TestStub",
    "TestBase",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    Optional,
)

import betterproto2
import grpclib
from betterproto2.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto2.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class Input(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False)
class Output(betterproto2.Message):
    double_value: "Optional[Optional[float]]" = betterproto2.message_field(1, optional=True)
    float_value: "Optional[Optional[float]]" = betterproto2.message_field(2, optional=True)
    int64_value: "Optional[Optional[int]]" = betterproto2.message_field(3, optional=True)
    uint64_value: "Optional[Optional[int]]" = betterproto2.message_field(4, optional=True)
    int32_value: "Optional[Optional[int]]" = betterproto2.message_field(5, optional=True)
    uint32_value: "Optional[Optional[int]]" = betterproto2.message_field(6, optional=True)
    bool_value: "Optional[Optional[bool]]" = betterproto2.message_field(7, optional=True)
    string_value: "Optional[Optional[str]]" = betterproto2.message_field(8, optional=True)
    bytes_value: "Optional[Optional[bytes]]" = betterproto2.message_field(9, optional=True)


class TestStub(betterproto2.ServiceStub):
    """
    Tests that wrapped values are supported as part of output message
    """

    async def get_output(
        self,
        input: "Input | None" = None,
        *,
        timeout: Optional[float] = None,
        deadline: "Optional[Deadline]" = None,
        metadata: "Optional[MetadataLike]" = None,
    ) -> "Output":
        if input is None:
            input = Input()

        return await self._unary_unary(
            "/googletypes_response_embedded.Test/getOutput",
            input,
            Output,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class TestBase(ServiceBase):
    """
    Tests that wrapped values are supported as part of output message
    """

    async def get_output(self, input: "Input") -> "Output":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_output(self, stream: "grpclib.server.Stream[Input, Output]") -> None:
        request = await stream.recv_message()
        response = await self.get_output(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/googletypes_response_embedded.Test/getOutput": grpclib.const.Handler(
                self.__rpc_get_output,
                grpclib.const.Cardinality.UNARY_UNARY,
                Input,
                Output,
            ),
        }
