# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: import_parent_package_from_child.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """
    Tests generated imports when a message refers to a message defined in its parent package
    """

    message_implicit: "Optional[__parent__.ParentPackageMessage]" = betterproto2.message_field(1, optional=True)
    message_explicit: "Optional[__parent__.ParentPackageMessage]" = betterproto2.message_field(2, optional=True)


from ... import parent as __parent__
