# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pickling.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pickling.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epickling.proto\x12\x08pickling\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x06\n\x04Test\"\x11\n\x02\x46\x65\x12\x0b\n\x03\x61\x62\x63\x18\x01 \x01(\t\"\x11\n\x02\x46i\x12\x0b\n\x03\x61\x62\x63\x18\x01 \x01(\t\"\x11\n\x02\x46o\x12\x0b\n\x03\x61\x62\x63\x18\x01 \x01(\t\"\x9c\x02\n\nNestedData\x12\x37\n\nstruct_foo\x18\x01 \x03(\x0b\x32#.pickling.NestedData.StructFooEntry\x12?\n\x0fmap_str_any_bar\x18\x02 \x03(\x0b\x32&.pickling.NestedData.MapStrAnyBarEntry\x1aI\n\x0eStructFooEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct:\x02\x38\x01\x1aI\n\x11MapStrAnyBarEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\"\x97\x02\n\x07\x43omplex\x12\x0f\n\x07\x66oo_str\x18\x01 \x01(\t\x12\x1a\n\x02\x66\x65\x18\x03 \x01(\x0b\x32\x0c.pickling.FeH\x00\x12\x1a\n\x02\x66i\x18\x04 \x01(\x0b\x32\x0c.pickling.FiH\x00\x12\x1a\n\x02\x66o\x18\x05 \x01(\x0b\x32\x0c.pickling.FoH\x00\x12)\n\x0bnested_data\x18\x06 \x01(\x0b\x32\x14.pickling.NestedData\x12/\n\x07mapping\x18\x07 \x03(\x0b\x32\x1e.pickling.Complex.MappingEntry\x1a\x44\n\x0cMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x42\x05\n\x03grp\"7\n\x0ePickledMessage\x12\x0b\n\x03\x66oo\x18\x01 \x01(\x08\x12\x0b\n\x03\x62\x61r\x18\x02 \x01(\x05\x12\x0b\n\x03\x62\x61z\x18\x03 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pickling_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NESTEDDATA_STRUCTFOOENTRY']._loaded_options = None
  _globals['_NESTEDDATA_STRUCTFOOENTRY']._serialized_options = b'8\001'
  _globals['_NESTEDDATA_MAPSTRANYBARENTRY']._loaded_options = None
  _globals['_NESTEDDATA_MAPSTRANYBARENTRY']._serialized_options = b'8\001'
  _globals['_COMPLEX_MAPPINGENTRY']._loaded_options = None
  _globals['_COMPLEX_MAPPINGENTRY']._serialized_options = b'8\001'
  _globals['_TEST']._serialized_start=85
  _globals['_TEST']._serialized_end=91
  _globals['_FE']._serialized_start=93
  _globals['_FE']._serialized_end=110
  _globals['_FI']._serialized_start=112
  _globals['_FI']._serialized_end=129
  _globals['_FO']._serialized_start=131
  _globals['_FO']._serialized_end=148
  _globals['_NESTEDDATA']._serialized_start=151
  _globals['_NESTEDDATA']._serialized_end=435
  _globals['_NESTEDDATA_STRUCTFOOENTRY']._serialized_start=287
  _globals['_NESTEDDATA_STRUCTFOOENTRY']._serialized_end=360
  _globals['_NESTEDDATA_MAPSTRANYBARENTRY']._serialized_start=362
  _globals['_NESTEDDATA_MAPSTRANYBARENTRY']._serialized_end=435
  _globals['_COMPLEX']._serialized_start=438
  _globals['_COMPLEX']._serialized_end=717
  _globals['_COMPLEX_MAPPINGENTRY']._serialized_start=642
  _globals['_COMPLEX_MAPPINGENTRY']._serialized_end=710
  _globals['_PICKLEDMESSAGE']._serialized_start=719
  _globals['_PICKLEDMESSAGE']._serialized_end=774
# @@protoc_insertion_point(module_scope)
