# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: casing_message_field_uppercase.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    uppercase: "int" = betterproto2.int32_field(1)
    uppercase_v2: "int" = betterproto2.int32_field(2)
    upper_camel_case: "int" = betterproto2.int32_field(3)
