# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: casing_message_field_uppercase.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    uppercase: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    UPPERCASE_V2: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    UPPER_CAMEL_CASE: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)


default_message_pool.register_message("casing_message_field_uppercase", "Test", Test)
