# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: messages.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "DoThingRequest",
    "DoThingResponse",
    "GetThingRequest",
    "GetThingResponse",
)

import datetime
from typing import (
    TYPE_CHECKING,
    List,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class DoThingRequest(betterproto2.Message):
    name: "str" = betterproto2.string_field(1)
    comments: "List[str]" = betterproto2.string_field(2, repeated=True)
    """
    use `repeated` so we can check if `List` is correctly imported
    """
    when: "Optional[datetime.datetime]" = betterproto2.message_field(3, optional=True)
    """
    use google types `timestamp` and `duration` so we can check
    if everything from `datetime` is correctly imported
    """
    duration: "Optional[datetime.timedelta]" = betterproto2.message_field(4, optional=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class DoThingResponse(betterproto2.Message):
    names: "List[str]" = betterproto2.string_field(1, repeated=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class GetThingRequest(betterproto2.Message):
    name: "str" = betterproto2.string_field(1)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class GetThingResponse(betterproto2.Message):
    name: "str" = betterproto2.string_field(1)
    version: "int" = betterproto2.int32_field(2)
