# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: casing.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "MyEnum",
    "SnakeCaseMessage",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


class MyEnum(betterproto2.Enum):
    ZERO = 0

    ONE = 1

    TWO = 2

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SnakeCaseMessage(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    camel_case: "int" = betterproto2.int32_field(1)
    snake_case: "MyEnum" = betterproto2.enum_field(2, enum_default_value=lambda: MyEnum.try_value(0))
    snake_case_message: "Optional[SnakeCaseMessage]" = betterproto2.message_field(3, optional=True)
    uppercase: "int" = betterproto2.int32_field(4)
