# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: empty_service.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "TestStub",
    "TestBase",
)


from typing import (
    TYPE_CHECKING,
    Dict,
)

import betterproto2
import grpclib
from betterproto2.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server


class TestStub(betterproto2.ServiceStub):
    pass


class TestBase(ServiceBase):
    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {}
