# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: empty_service.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "TestStub",
    "TestBase",
)


import betterproto2
from betterproto2.grpc.grpclib_server import ServiceBase

betterproto2.check_compiler_version("0.2.4")


class TestStub(betterproto2.ServiceStub):
    pass


class TestBase(ServiceBase):
    def __mapping__(self) -> "dict[str, grpclib.const.Handler":
        return {}
