site_name: Betterproto2
site_url: https://betterproto.github.io/python-betterproto2-compiler/
theme:
  name: material
  palette:
    primary: deep orange
    accent: deep orange

  features:
   - navigation.tabs

nav:
  - Betterproto2: https://betterproto.github.io/python-betterproto2/
  - Betterproto2 compiler:
     - index.md
     - Getting started: getting-started.md

plugins:
- mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences