site_name: Betterproto2 Compiler
site_url: https://betterproto.github.io/python-betterproto2-compiler/
theme:
  name: material
  palette:
    primary: deep orange
    accent: deep orange

plugins:
- mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences