# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: repeated_duration_timestamp.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

import datetime
from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.3.0")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    times: "list[datetime.datetime]" = betterproto2.field(
        1, betterproto2.FieldDescriptorProtoType.TYPE_MESSAGE, repeated=True
    )

    durations: "list[datetime.timedelta]" = betterproto2.field(
        2, betterproto2.FieldDescriptorProtoType.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("repeated_duration_timestamp", "Test", Test)
