# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: google_impl_behavior_equivalence.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Empty",
    "Foo",
    "Request",
    "Spam",
    "Test",
)

import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic import model_validator
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Empty(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Foo(betterproto2.Message):
    bar: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Request(betterproto2.Message):
    foo: "Optional[Empty]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Spam(betterproto2.Message):
    ts: "Optional[datetime.datetime]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """


    Oneofs:
        - group:
    """

    string: "Optional[str]" = betterproto2.field(1, betterproto2.TYPE_STRING, optional=True, group="group")
    integer: "Optional[int]" = betterproto2.field(2, betterproto2.TYPE_INT64, optional=True, group="group")
    foo: "Optional[Foo]" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True, group="group")

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)
