# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: rpc_empty_input_message.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Response",
    "Test",
    "ServiceStub",
    "ServiceBase",
)


from typing import (
    TYPE_CHECKING,
    Dict,
    Optional,
)

import betterproto2
import grpclib
from betterproto2.grpc.grpclib_server import ServiceBase
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    import grpclib.server
    from betterproto2.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Response(betterproto2.Message):
    v: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    pass


class ServiceStub(betterproto2.ServiceStub):
    async def read(
        self,
        test: "Test | None" = None,
        *,
        timeout: Optional[float] = None,
        deadline: "Optional[Deadline]" = None,
        metadata: "Optional[MetadataLike]" = None,
    ) -> "Response":
        if test is None:
            test = Test()

        return await self._unary_unary(
            "/rpc_empty_input_message.Service/read",
            test,
            Response,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class ServiceBase(ServiceBase):
    async def read(self, test: "Test") -> "Response":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_read(self, stream: "grpclib.server.Stream[Test, Response]") -> None:
        request = await stream.recv_message()
        response = await self.read(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/rpc_empty_input_message.Service/read": grpclib.const.Handler(
                self.__rpc_read,
                grpclib.const.Cardinality.UNARY_UNARY,
                Test,
                Response,
            ),
        }
