# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_nested_child_package_from_root.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'import_nested_child_package_from_root.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import child_pb2 as child__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+import_nested_child_package_from_root.proto\x12%import_nested_child_package_from_root\x1a\x0b\x63hild.proto\"c\n\x04Test\x12[\n\x05\x63hild\x18\x01 \x01(\x0b\x32L.import_nested_child_package_from_root.package.child.otherchild.ChildMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'import_nested_child_package_from_root_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEST']._serialized_start=99
  _globals['_TEST']._serialized_end=198
# @@protoc_insertion_point(module_scope)
