# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: googletypes.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

import datetime
from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    maybe: "Optional[Optional[bool]]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, wraps=betterproto2.TYPE_BOOL, optional=True
    )
    ts: "Optional[datetime.datetime]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)
    duration: "Optional[datetime.timedelta]" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True)
    important: "Optional[Optional[int]]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, wraps=betterproto2.TYPE_INT32, optional=True
    )
    empty: "Optional[betterproto2_lib_google_protobuf.Empty]" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )


import betterproto2.lib.google.protobuf as betterproto2_lib_google_protobuf
