# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: timestamp_dict_encode.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

import datetime
from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    ts: "Optional[datetime.datetime]" = betterproto2.message_field(1, optional=True)
