# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: googletypes.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    maybe: "Optional[Optional[bool]]" = betterproto2.message_field(1, wraps=betterproto2.TYPE_BOOL, optional=True)
    ts: "Optional[datetime.datetime]" = betterproto2.message_field(2, optional=True)
    duration: "Optional[datetime.timedelta]" = betterproto2.message_field(3, optional=True)
    important: "Optional[Optional[int]]" = betterproto2.message_field(4, wraps=betterproto2.TYPE_INT32, optional=True)
    empty: "Optional[betterproto2_lib_pydantic_google_protobuf.Empty]" = betterproto2.message_field(5, optional=True)


import betterproto2.lib.pydantic.google.protobuf as betterproto2_lib_pydantic_google_protobuf
