# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: import_child_package_from_package.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """
    Tests generated imports when a message in a package refers to a message in a nested child package.
    """

    message: "Optional[package.PackageMessage]" = betterproto2.message_field(1, optional=True)


from . import package
