# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: oneof_enum.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Signal",
    "Move",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic import model_validator
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


class Signal(betterproto2.Enum):
    PASS = 0

    RESIGN = 1

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Move(betterproto2.Message):
    x: "int" = betterproto2.int32_field(1)
    y: "int" = betterproto2.int32_field(2)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    signal: "Optional[Signal]" = betterproto2.enum_field(
        1, optional=True, enum_default_value=lambda: Signal.try_value(0), group="action"
    )
    move: "Optional[Move]" = betterproto2.message_field(2, optional=True, group="action")

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)
