# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: oneof_enum.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Signal",
    "Move",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic import model_validator
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


class Signal(betterproto2.Enum):
    PASS = 0

    RESIGN = 1

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Move(betterproto2.Message):
    x: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    y: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """


    Oneofs:
        - action:
    """

    signal: "Optional[Signal]" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, optional=True, default_factory=lambda: Signal.try_value(0), group="action"
    )
    move: "Optional[Move]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True, group="action")

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)
