# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_child_scoping_rules.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'import_child_scoping_rules.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import package_pb2 as package__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n import_child_scoping_rules.proto\x12\x1aimport_child_scoping_rules\x1a\rpackage.proto\"<\n\x04Test\x12\x34\n\x03msg\x18\x01 \x01(\x0b\x32\'.import_child_scoping_rules.aaa.bbb.Msgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'import_child_scoping_rules_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEST']._serialized_start=79
  _globals['_TEST']._serialized_end=139
# @@protoc_insertion_point(module_scope)
