# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: package.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'package.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import child_pb2 as child__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpackage.proto\x12\"import_child_scoping_rules.aaa.bbb\x1a\x0b\x63hild.proto\"\xde\x02\n\x03Msg\x12\x43\n\x01\x61\x18\x01 \x01(\x0b\x32\x38.import_child_scoping_rules.aaa.bbb.ccc.ddd.ChildMessage\x12\x43\n\x01\x62\x18\x02 \x01(\x0b\x32\x38.import_child_scoping_rules.aaa.bbb.ccc.ddd.ChildMessage\x12\x43\n\x01\x63\x18\x03 \x01(\x0b\x32\x38.import_child_scoping_rules.aaa.bbb.ccc.ddd.ChildMessage\x12\x43\n\x01\x64\x18\x04 \x01(\x0b\x32\x38.import_child_scoping_rules.aaa.bbb.ccc.ddd.ChildMessage\x12\x43\n\x01\x65\x18\x05 \x01(\x0b\x32\x38.import_child_scoping_rules.aaa.bbb.ccc.ddd.ChildMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'package_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSG']._serialized_start=67
  _globals['_MSG']._serialized_end=417
# @@protoc_insertion_point(module_scope)
