# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: float.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


import betterproto2
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """
    Some documentation about the Test message.
    """

    positive: "float" = betterproto2.field(1, betterproto2.TYPE_DOUBLE)

    negative: "float" = betterproto2.field(2, betterproto2.TYPE_DOUBLE)

    nan: "float" = betterproto2.field(3, betterproto2.TYPE_DOUBLE)

    three: "float" = betterproto2.field(4, betterproto2.TYPE_DOUBLE)

    three_point_one_four: "float" = betterproto2.field(5, betterproto2.TYPE_DOUBLE)

    neg_three: "float" = betterproto2.field(6, betterproto2.TYPE_DOUBLE)

    neg_three_point_one_four: "float" = betterproto2.field(7, betterproto2.TYPE_DOUBLE)


default_message_pool.register_message("float", "Test", Test)
