# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: package.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Msg",)

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class Msg(betterproto2.Message):
    a: "ccc_ddd.ChildMessage | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)

    b: "ccc_ddd.ChildMessage | None" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)

    c: "ccc_ddd.ChildMessage | None" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True)

    d: "ccc_ddd.ChildMessage | None" = betterproto2.field(4, betterproto2.TYPE_MESSAGE, optional=True)

    e: "ccc_ddd.ChildMessage | None" = betterproto2.field(5, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("import_child_scoping_rules.aaa.bbb", "Msg", Msg)


from .ccc import ddd as ccc_ddd
