# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: package.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Msg",)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False)
class Msg(betterproto2.Message):
    a: "Optional[ccc_ddd.ChildMessage]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    b: "Optional[ccc_ddd.ChildMessage]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)
    c: "Optional[ccc_ddd.ChildMessage]" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True)
    d: "Optional[ccc_ddd.ChildMessage]" = betterproto2.field(4, betterproto2.TYPE_MESSAGE, optional=True)
    e: "Optional[ccc_ddd.ChildMessage]" = betterproto2.field(5, betterproto2.TYPE_MESSAGE, optional=True)


from .ccc import ddd as ccc_ddd
