# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: import_child_scoping_rules.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    msg: "aaa_bbb.Msg | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("import_child_scoping_rules", "Test", Test)


from .aaa import bbb as aaa_bbb
