# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: import_child_scoping_rules.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    msg: "Optional[aaa_bbb.Msg]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


from .aaa import bbb as aaa_bbb
