# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: child.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """
    Verify that we can import root message from child package
    """

    message: "Optional[__import_root_package_from_child__.RootMessage]" = betterproto2.message_field(1, optional=True)


from ... import import_root_package_from_child as __import_root_package_from_child__
