# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_wrapping.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'message_wrapping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16message_wrapping.proto\x12\x10message_wrapping\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x8a\x02\n\nMapMessage\x12\x34\n\x04map1\x18\x01 \x03(\x0b\x32&.message_wrapping.MapMessage.Map1Entry\x12\x34\n\x04map2\x18\x02 \x03(\x0b\x32&.message_wrapping.MapMessage.Map2Entry\x1aH\n\tMap1Entry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.FloatValue:\x02\x38\x01\x1a\x46\n\tMap2Entry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_wrapping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPMESSAGE_MAP1ENTRY']._loaded_options = None
  _globals['_MAPMESSAGE_MAP1ENTRY']._serialized_options = b'8\001'
  _globals['_MAPMESSAGE_MAP2ENTRY']._loaded_options = None
  _globals['_MAPMESSAGE_MAP2ENTRY']._serialized_options = b'8\001'
  _globals['_MAPMESSAGE']._serialized_start=109
  _globals['_MAPMESSAGE']._serialized_end=375
  _globals['_MAPMESSAGE_MAP1ENTRY']._serialized_start=231
  _globals['_MAPMESSAGE_MAP1ENTRY']._serialized_end=303
  _globals['_MAPMESSAGE_MAP2ENTRY']._serialized_start=305
  _globals['_MAPMESSAGE_MAP2ENTRY']._serialized_end=375
# @@protoc_insertion_point(module_scope)
