# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: empty_repeated.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "MessageA",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    List,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MessageA(betterproto2.Message):
    values: "List[float]" = betterproto2.field(1, betterproto2.TYPE_FLOAT, repeated=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    msg: "List[MessageA]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, repeated=True)
