# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: empty_repeated.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "MessageA",
    "Test",
)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MessageA(betterproto2.Message):
    values: "list[typing.Annotated[float, pydantic.AfterValidator(betterproto2.validators.validate_float32)]]" = (
        betterproto2.field(1, betterproto2.TYPE_FLOAT, repeated=True)
    )


default_message_pool.register_message("empty_repeated", "MessageA", MessageA)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    msg: "list[MessageA]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, repeated=True)


default_message_pool.register_message("empty_repeated", "Test", Test)
