# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: documentation.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64ocumentation.proto\x12\rdocumentation\"/\n\x04Test\x12\t\n\x01x\x18\x01 \x01(\r\x12\x0b\n\x01\x61\x18\x02 \x01(\x05H\x00\x42\x0f\n\roneof_example*\x18\n\x04\x45num\x12\x10\n\x0c\x45num_Variant\x10\x00\x32:\n\x07Service\x12/\n\x03get\x12\x13.documentation.Test\x1a\x13.documentation.Testb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'documentation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENUM']._serialized_start=87
  _globals['_ENUM']._serialized_end=111
  _globals['_TEST']._serialized_start=38
  _globals['_TEST']._serialized_end=85
  _globals['_SERVICE']._serialized_start=113
  _globals['_SERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
