# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: features.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Bar",
    "Empty",
    "Enum",
    "EnumMsg",
    "Foo",
    "IntMsg",
    "JsonCasingMsg",
    "MsgA",
    "MsgB",
    "MsgC",
    "MsgD",
    "MsgE",
    "Newer",
    "Older",
    "OneofMsg",
    "OptionalBoolMsg",
    "OptionalDatetimeMsg",
    "TimeMsg",
)

import datetime
from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


class Enum(betterproto2.Enum):
    ZERO = 0

    ONE = 1


@dataclass(eq=False, repr=False)
class Bar(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("features", "Bar", Bar)


@dataclass(eq=False, repr=False)
class Empty(betterproto2.Message):
    pass


default_message_pool.register_message("features", "Empty", Empty)


@dataclass(eq=False, repr=False)
class EnumMsg(betterproto2.Message):
    enum: "Enum" = betterproto2.field(1, betterproto2.TYPE_ENUM, default_factory=lambda: Enum(0))


default_message_pool.register_message("features", "EnumMsg", EnumMsg)


@dataclass(eq=False, repr=False)
class Foo(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    child: "Bar | None" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("features", "Foo", Foo)


@dataclass(eq=False, repr=False)
class IntMsg(betterproto2.Message):
    val: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)


default_message_pool.register_message("features", "IntMsg", IntMsg)


@dataclass(eq=False, repr=False)
class JsonCasingMsg(betterproto2.Message):
    pascal_case: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    camel_case: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    snake_case: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)

    kabob_case: "int" = betterproto2.field(4, betterproto2.TYPE_INT32)


default_message_pool.register_message("features", "JsonCasingMsg", JsonCasingMsg)


@dataclass(eq=False, repr=False)
class MsgA(betterproto2.Message):
    some_int: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    some_double: "float" = betterproto2.field(2, betterproto2.TYPE_DOUBLE)

    some_str: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    some_bool: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)


default_message_pool.register_message("features", "MsgA", MsgA)


@dataclass(eq=False, repr=False)
class MsgB(betterproto2.Message):
    some_int: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    some_double: "float" = betterproto2.field(2, betterproto2.TYPE_DOUBLE)

    some_str: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    some_bool: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)

    some_default_int: "int" = betterproto2.field(5, betterproto2.TYPE_INT32)

    some_default_double: "float" = betterproto2.field(6, betterproto2.TYPE_DOUBLE)

    some_default_str: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)

    some_default_bool: "bool" = betterproto2.field(8, betterproto2.TYPE_BOOL)


default_message_pool.register_message("features", "MsgB", MsgB)


@dataclass(eq=False, repr=False)
class MsgC(betterproto2.Message):
    """


    Oneofs:
        - group1:
    """

    int_field: "int | None" = betterproto2.field(1, betterproto2.TYPE_INT32, optional=True, group="group1")

    string_field: "str | None" = betterproto2.field(2, betterproto2.TYPE_STRING, optional=True, group="group1")

    empty_field: "Empty | None" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True, group="group1")


default_message_pool.register_message("features", "MsgC", MsgC)


@dataclass(eq=False, repr=False)
class MsgD(betterproto2.Message):
    timestamps: "list[datetime.datetime]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.Timestamp, repeated=True
    )


default_message_pool.register_message("features", "MsgD", MsgD)


@dataclass(eq=False, repr=False)
class MsgE(betterproto2.Message):
    bool_field: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    int_field: "int | None" = betterproto2.field(2, betterproto2.TYPE_INT32, optional=True)


default_message_pool.register_message("features", "MsgE", MsgE)


@dataclass(eq=False, repr=False)
class Newer(betterproto2.Message):
    x: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    y: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    z: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)


default_message_pool.register_message("features", "Newer", Newer)


@dataclass(eq=False, repr=False)
class Older(betterproto2.Message):
    x: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)


default_message_pool.register_message("features", "Older", Older)


@dataclass(eq=False, repr=False)
class OneofMsg(betterproto2.Message):
    """


    Oneofs:
        - group1:
        - group2:
    """

    x: "int | None" = betterproto2.field(1, betterproto2.TYPE_INT32, optional=True, group="group1")

    y: "str | None" = betterproto2.field(2, betterproto2.TYPE_STRING, optional=True, group="group1")

    a: "IntMsg | None" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True, group="group2")

    b: "str | None" = betterproto2.field(4, betterproto2.TYPE_STRING, optional=True, group="group2")


default_message_pool.register_message("features", "OneofMsg", OneofMsg)


@dataclass(eq=False, repr=False)
class OptionalBoolMsg(betterproto2.Message):
    field: "bool | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.BoolValue, optional=True
    )


default_message_pool.register_message("features", "OptionalBoolMsg", OptionalBoolMsg)


@dataclass(eq=False, repr=False)
class OptionalDatetimeMsg(betterproto2.Message):
    field: "datetime.datetime | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.Timestamp, optional=True
    )


default_message_pool.register_message("features", "OptionalDatetimeMsg", OptionalDatetimeMsg)


@dataclass(eq=False, repr=False)
class TimeMsg(betterproto2.Message):
    timestamp: "datetime.datetime | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.Timestamp, optional=True
    )

    duration: "datetime.timedelta | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.Duration, optional=True
    )


default_message_pool.register_message("features", "TimeMsg", TimeMsg)


from ..google import protobuf as _google__protobuf__
