# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: recursivemessage.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Intermediate",
    "Test",
)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Intermediate(betterproto2.Message):
    number: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT32
    )

    child: "Test | None" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("recursivemessage", "Intermediate", Intermediate)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = (
        betterproto2.field(1, betterproto2.TYPE_STRING)
    )

    child: "Test | None" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)

    intermediate: "Intermediate | None" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("recursivemessage", "Test", Test)
