# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: regression_387.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "ParentElement",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    List,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ParentElement(betterproto2.Message):
    name: "str" = betterproto2.string_field(1)
    elems: "List[Test]" = betterproto2.message_field(2, repeated=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    id: "int" = betterproto2.uint64_field(1)
