# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: regression_387.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "ParentElement",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    List,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ParentElement(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    elems: "List[Test]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, repeated=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
