# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entry.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65ntry.proto\x12\x05\x65ntry\"*\n\x04Test\x12\"\n\x06\x65xport\x18\x01 \x03(\x0b\x32\x12.entry.ExportEntry\"\x1b\n\x0b\x45xportEntry\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEST']._serialized_start=22
  _globals['_TEST']._serialized_end=64
  _globals['_EXPORTENTRY']._serialized_start=66
  _globals['_EXPORTENTRY']._serialized_end=93
# @@protoc_insertion_point(module_scope)
