# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nestedtwice.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Test",
    "TestTop",
    "TestTopMiddle",
    "TestTopMiddleBottom",
    "TestTopMiddleEnumBottom",
    "TestTopMiddleTopMiddleBottom",
)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


class TestTopMiddleEnumBottom(betterproto2.Enum):
    """
    EnumBottom doc.
    """

    A = 0
    """
    EnumBottom.A doc. 
    """

    B = 1

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """
    Test doc.
    """

    top: "TestTop | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    """
    Test.top doc. 
    """


default_message_pool.register_message("nestedtwice", "Test", Test)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TestTop(betterproto2.Message):
    """
    Top doc.
    """

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = (
        betterproto2.field(1, betterproto2.TYPE_STRING)
    )
    """
    Top.name doc. 
    """

    middle: "TestTopMiddle | None" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("nestedtwice", "Test.Top", TestTop)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TestTopMiddle(betterproto2.Message):
    """
    Middle doc.
    """

    bottom: "list[TestTopMiddleBottom]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, repeated=True)
    """
    Middle.bottom doc. 
    """

    enum_bottom: "list[TestTopMiddleEnumBottom]" = betterproto2.field(3, betterproto2.TYPE_ENUM, repeated=True)

    top_middle_bottom: "list[TestTopMiddleTopMiddleBottom]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )

    bar: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)


default_message_pool.register_message("nestedtwice", "Test.Top.Middle", TestTopMiddle)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TestTopMiddleBottom(betterproto2.Message):
    """
    Bottom doc.
    """

    foo: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )
    """
    Bottom.foo doc. 
    """


default_message_pool.register_message("nestedtwice", "Test.Top.Middle.Bottom", TestTopMiddleBottom)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TestTopMiddleTopMiddleBottom(betterproto2.Message):
    """
    TopMiddleBottom doc.
    """

    a: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )
    """
    TopMiddleBottom.a doc.
    """


default_message_pool.register_message("nestedtwice", "Test.Top.Middle.TopMiddleBottom", TestTopMiddleTopMiddleBottom)
