# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ref.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    greeting: "Optional[_repeatedmessage__.Sub]" = betterproto2.message_field(1, optional=True)


from .. import repeatedmessage as _repeatedmessage__
