# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ref.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


import betterproto2
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    greeting: "_repeatedmessage__.Sub | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("ref", "Test", Test)


from .. import repeatedmessage as _repeatedmessage__
