# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: casing_inner_class.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Test",
    "TestInnerClass",
)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    inner: "TestInnerClass | None" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("casing_inner_class", "Test", Test)


@dataclass(eq=False, repr=False)
class TestInnerClass(betterproto2.Message):
    old_exp: "int" = betterproto2.field(1, betterproto2.TYPE_SINT32)


default_message_pool.register_message("casing_inner_class", "Test.inner_class", TestInnerClass)
