# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: casing_inner_class.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Test",
    "TestInnerClass",
)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    inner: "Optional[TestInnerClass]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TestInnerClass(betterproto2.Message):
    old_exp: "int" = betterproto2.field(1, betterproto2.TYPE_SINT32)
