# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: validation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'validation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10validation.proto\x12\nvalidation\"\x94\x02\n\x07Message\x12\x13\n\x0bint32_value\x18\x01 \x01(\x05\x12\x13\n\x0bint64_value\x18\x02 \x01(\x03\x12\x14\n\x0cuint32_value\x18\x03 \x01(\r\x12\x14\n\x0cuint64_value\x18\x04 \x01(\x04\x12\x14\n\x0csint32_value\x18\x05 \x01(\x11\x12\x14\n\x0csint64_value\x18\x06 \x01(\x12\x12\x15\n\rfixed32_value\x18\x07 \x01(\x07\x12\x15\n\rfixed64_value\x18\x08 \x01(\x06\x12\x16\n\x0esfixed32_value\x18\t \x01(\x0f\x12\x16\n\x0esfixed64_value\x18\n \x01(\x10\x12\x13\n\x0b\x66loat_value\x18\x0b \x01(\x02\x12\x14\n\x0cstring_value\x18\x0c \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'validation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=33
  _globals['_MESSAGE']._serialized_end=309
# @@protoc_insertion_point(module_scope)
