# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: repeatedmessage.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Sub",
    "Test",
)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class Sub(betterproto2.Message):
    greeting: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("repeatedmessage", "Sub", Sub)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    greetings: "list[Sub]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, repeated=True)


default_message_pool.register_message("repeatedmessage", "Test", Test)
