# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: import_root_sibling.proto, sibling.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "SiblingMessage",
    "Test",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False)
class SiblingMessage(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """
    Tests generated imports when a message in the root package refers to another message in the root package

    """

    sibling: "Optional[SiblingMessage]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
