# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: test.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """
    Verify that we can import a message unrelated to us, in a subpackage with the same name as us.

    """

    message: "Optional[__cousin_subpackage__.CousinMessage]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


from ...cousin import subpackage as __cousin_subpackage__
