# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: fixed.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    foo: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = betterproto2.field(1, betterproto2.TYPE_FIXED32)

    bar: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        2, betterproto2.TYPE_SFIXED32
    )

    baz: "typing.Annotated[int, pydantic.Field(ge=0, le=2**64 - 1)]" = betterproto2.field(3, betterproto2.TYPE_FIXED64)

    qux: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        4, betterproto2.TYPE_SFIXED64
    )


default_message_pool.register_message("fixed", "Test", Test)
