# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simple_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'simple_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14simple_service.proto\x12\x0esimple_service\"\x18\n\x07Request\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xab\x02\n\rSimpleService\x12\x42\n\rGetUnaryUnary\x12\x17.simple_service.Request\x1a\x18.simple_service.Response\x12\x45\n\x0eGetUnaryStream\x12\x17.simple_service.Request\x1a\x18.simple_service.Response0\x01\x12\x45\n\x0eGetStreamUnary\x12\x17.simple_service.Request\x1a\x18.simple_service.Response(\x01\x12H\n\x0fGetStreamStream\x12\x17.simple_service.Request\x1a\x18.simple_service.Response(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simple_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=40
  _globals['_REQUEST']._serialized_end=64
  _globals['_RESPONSE']._serialized_start=66
  _globals['_RESPONSE']._serialized_end=93
  _globals['_SIMPLESERVICE']._serialized_start=96
  _globals['_SIMPLESERVICE']._serialized_end=395
# @@protoc_insertion_point(module_scope)
