# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nested.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "TestMsg",
    "Sibling",
    "Test",
    "TestNested",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


class TestMsg(betterproto2.Enum):
    """
    This is the nested enum.
    """

    NONE = 0

    THIS = 1


@dataclass(eq=False, repr=False)
class Sibling(betterproto2.Message):
    foo: "int" = betterproto2.int32_field(1)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """
    A test message with a nested message inside of it.
    """

    nested: "Optional[TestNested]" = betterproto2.message_field(1, optional=True)
    sibling: "Optional[Sibling]" = betterproto2.message_field(2, optional=True)
    sibling2: "Optional[Sibling]" = betterproto2.message_field(3, optional=True)
    msg: "TestMsg" = betterproto2.enum_field(4, enum_default_value=lambda: TestMsg.try_value(0))


@dataclass(eq=False, repr=False)
class TestNested(betterproto2.Message):
    """
    This is the nested type.
    """

    count: "int" = betterproto2.int32_field(1)
    """
    Stores a simple counter.
    """
