# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: regression_414.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    List,
)

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    body: "bytes" = betterproto2.bytes_field(1)
    auth: "bytes" = betterproto2.bytes_field(2)
    signatures: "List[bytes]" = betterproto2.bytes_field(3, repeated=True)
