# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: repeated_duration_timestamp.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

import datetime
from typing import (
    TYPE_CHECKING,
    List,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    times: "List[datetime.datetime]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, repeated=True)
    durations: "List[datetime.timedelta]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, repeated=True)
