# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: import_root_sibling.proto, sibling.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "SiblingMessage",
    "Test",
)


import betterproto2
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SiblingMessage(betterproto2.Message):
    pass


default_message_pool.register_message("import_root_sibling", "SiblingMessage", SiblingMessage)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """
    Tests generated imports when a message in the root package refers to another message in the root package
    """

    sibling: "SiblingMessage | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("import_root_sibling", "Test", Test)
