# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: import_root_sibling.proto, sibling.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "SiblingMessage",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SiblingMessage(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """
    Tests generated imports when a message in the root package refers to another message in the root package
    """

    sibling: "Optional[SiblingMessage]" = betterproto2.message_field(1, optional=True)
