# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nested2.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "GamePlayerRace",
    "Game",
    "GamePlayer",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


class GamePlayerRace(betterproto2.Enum):
    human = 0

    orc = 1

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Game(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class GamePlayer(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    game: "Optional[Game]" = betterproto2.message_field(1, optional=True)
    game_player: "Optional[GamePlayer]" = betterproto2.message_field(2, optional=True)
    game_player_race: "GamePlayerRace" = betterproto2.enum_field(
        3, enum_default_value=lambda: GamePlayerRace.try_value(0)
    )
    weapon: "Optional[equipment.Weapon]" = betterproto2.message_field(4, optional=True)


from . import equipment
