# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nested2.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "GamePlayerRace",
    "Game",
    "GamePlayer",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


class GamePlayerRace(betterproto2.Enum):
    human = 0

    orc = 1

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Game(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class GamePlayer(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    game: "Optional[Game]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    game_player: "Optional[GamePlayer]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)
    game_player_race: "GamePlayerRace" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: GamePlayerRace.try_value(0)
    )
    weapon: "Optional[equipment.Weapon]" = betterproto2.field(4, betterproto2.TYPE_MESSAGE, optional=True)


from . import equipment
