# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: package_message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import child_pb2 as child__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15package_message.proto\x12)import_child_package_from_package.package\x1a\x0b\x63hild.proto\"a\n\x0ePackageMessage\x12O\n\x01\x63\x18\x01 \x01(\x0b\x32\x44.import_child_package_from_package.package.childpackage.ChildMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'package_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PACKAGEMESSAGE']._serialized_start=81
  _globals['_PACKAGEMESSAGE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
