# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: repeatedpacked.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from typing import (
    TYPE_CHECKING,
    List,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    counts: "List[int]" = betterproto2.field(1, betterproto2.TYPE_INT32, repeated=True)
    signed: "List[int]" = betterproto2.field(2, betterproto2.TYPE_SINT64, repeated=True)
    fixed: "List[float]" = betterproto2.field(3, betterproto2.TYPE_DOUBLE, repeated=True)
