# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: repeatedpacked.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from typing import (
    TYPE_CHECKING,
    List,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    counts: "List[int]" = betterproto2.int32_field(1, repeated=True)
    signed: "List[int]" = betterproto2.sint64_field(2, repeated=True)
    fixed: "List[float]" = betterproto2.double_field(3, repeated=True)
