# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: repeatedpacked.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    counts: "list[typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]]" = betterproto2.field(
        1, betterproto2.TYPE_INT32, repeated=True
    )

    signed: "list[typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]]" = betterproto2.field(
        2, betterproto2.TYPE_SINT64, repeated=True
    )

    fixed: "list[float]" = betterproto2.field(3, betterproto2.TYPE_DOUBLE, repeated=True)


default_message_pool.register_message("repeatedpacked", "Test", Test)
