# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: oneof_default_value_serialization.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Message",
    "NestedMessage",
    "Test",
)

import datetime
import typing

import betterproto2
import pydantic
from pydantic import model_validator
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Message(betterproto2.Message):
    value: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT64
    )


default_message_pool.register_message("oneof_default_value_serialization", "Message", Message)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class NestedMessage(betterproto2.Message):
    """


    Oneofs:
        - value_type:
    """

    id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT64
    )

    wrapped_message_value: "Message | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="value_type"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


default_message_pool.register_message("oneof_default_value_serialization", "NestedMessage", NestedMessage)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """


    Oneofs:
        - value_type:
    """

    bool_value: "bool | None" = betterproto2.field(1, betterproto2.TYPE_BOOL, optional=True, group="value_type")

    int64_value: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)] | None" = betterproto2.field(
        2, betterproto2.TYPE_INT64, optional=True, group="value_type"
    )

    timestamp_value: "datetime.datetime | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.Timestamp, optional=True, group="value_type"
    )

    duration_value: "datetime.timedelta | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.Duration, optional=True, group="value_type"
    )

    wrapped_message_value: "Message | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="value_type"
    )

    wrapped_nested_message_value: "NestedMessage | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="value_type"
    )

    wrapped_bool_value: "bool | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.BoolValue, optional=True, group="value_type"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


default_message_pool.register_message("oneof_default_value_serialization", "Test", Test)


from ..google import protobuf as _google__protobuf__
