# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: oneof_default_value_serialization.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Message",
    "NestedMessage",
    "Test",
)

import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic import model_validator
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Message(betterproto2.Message):
    value: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class NestedMessage(betterproto2.Message):
    """


    Oneofs:
        - value_type:
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    wrapped_message_value: "Optional[Message]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="value_type"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """


    Oneofs:
        - value_type:
    """

    bool_value: "Optional[bool]" = betterproto2.field(1, betterproto2.TYPE_BOOL, optional=True, group="value_type")
    int64_value: "Optional[int]" = betterproto2.field(2, betterproto2.TYPE_INT64, optional=True, group="value_type")
    timestamp_value: "Optional[datetime.datetime]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="value_type"
    )
    duration_value: "Optional[datetime.timedelta]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="value_type"
    )
    wrapped_message_value: "Optional[Message]" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="value_type"
    )
    wrapped_nested_message_value: "Optional[NestedMessage]" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="value_type"
    )
    wrapped_bool_value: "Optional[Optional[bool]]" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, wraps=betterproto2.TYPE_BOOL, optional=True, group="value_type"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)
