# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: oneof_default_value_serialization.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Message",
    "NestedMessage",
    "Test",
)

import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic import model_validator
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Message(betterproto2.Message):
    value: "int" = betterproto2.int64_field(1)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class NestedMessage(betterproto2.Message):
    id: "int" = betterproto2.int64_field(1)
    wrapped_message_value: "Optional[Message]" = betterproto2.message_field(2, optional=True, group="value_type")

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    bool_value: "Optional[bool]" = betterproto2.bool_field(1, optional=True, group="value_type")
    int64_value: "Optional[int]" = betterproto2.int64_field(2, optional=True, group="value_type")
    timestamp_value: "Optional[datetime.datetime]" = betterproto2.message_field(3, optional=True, group="value_type")
    duration_value: "Optional[datetime.timedelta]" = betterproto2.message_field(4, optional=True, group="value_type")
    wrapped_message_value: "Optional[Message]" = betterproto2.message_field(5, optional=True, group="value_type")
    wrapped_nested_message_value: "Optional[NestedMessage]" = betterproto2.message_field(
        6, optional=True, group="value_type"
    )
    wrapped_bool_value: "Optional[Optional[bool]]" = betterproto2.message_field(
        7, wraps=betterproto2.TYPE_BOOL, optional=True, group="value_type"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)
