# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: posts_v1.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Post",)


import betterproto2
from pydantic.dataclasses import dataclass

from ....message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Post(betterproto2.Message):
    pass


default_message_pool.register_message("import_packages_same_name.posts.v1", "Post", Post)
