# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: oneof.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "MixedDrink",
    "Test",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class MixedDrink(betterproto2.Message):
    shots: "int" = betterproto2.int32_field(1)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    pitied: "Optional[int]" = betterproto2.int32_field(1, optional=True, group="foo")
    pitier: "Optional[str]" = betterproto2.string_field(2, optional=True, group="foo")
    just_a_regular_field: "int" = betterproto2.int32_field(3)
    drinks: "Optional[int]" = betterproto2.int32_field(11, optional=True, group="bar")
    bar_name: "Optional[str]" = betterproto2.string_field(12, optional=True, group="bar")
    mixed_drink: "Optional[MixedDrink]" = betterproto2.message_field(13, optional=True, group="bar")
