# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: oneof.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "MixedDrink",
    "Test",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False)
class MixedDrink(betterproto2.Message):
    shots: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """


    Oneofs:
        - foo:
        - bar:
    """

    pitied: "Optional[int]" = betterproto2.field(1, betterproto2.TYPE_INT32, optional=True, group="foo")
    pitier: "Optional[str]" = betterproto2.field(2, betterproto2.TYPE_STRING, optional=True, group="foo")
    just_a_regular_field: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)
    drinks: "Optional[int]" = betterproto2.field(11, betterproto2.TYPE_INT32, optional=True, group="bar")
    bar_name: "Optional[str]" = betterproto2.field(12, betterproto2.TYPE_STRING, optional=True, group="bar")
    mixed_drink: "Optional[MixedDrink]" = betterproto2.field(13, betterproto2.TYPE_MESSAGE, optional=True, group="bar")
