# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: package.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Weapon",)


from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False)
class Weapon(betterproto2.Message):
    pass
