# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: validation.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Message",)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class Message(betterproto2.Message):
    int32_value: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    int64_value: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)

    uint32_value: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)

    uint64_value: "int" = betterproto2.field(4, betterproto2.TYPE_UINT64)

    sint32_value: "int" = betterproto2.field(5, betterproto2.TYPE_SINT32)

    sint64_value: "int" = betterproto2.field(6, betterproto2.TYPE_SINT64)

    fixed32_value: "int" = betterproto2.field(7, betterproto2.TYPE_FIXED32)

    fixed64_value: "int" = betterproto2.field(8, betterproto2.TYPE_FIXED64)

    sfixed32_value: "int" = betterproto2.field(9, betterproto2.TYPE_SFIXED32)

    sfixed64_value: "int" = betterproto2.field(10, betterproto2.TYPE_SFIXED64)

    float_value: "float" = betterproto2.field(11, betterproto2.TYPE_FLOAT)

    string_value: "str" = betterproto2.field(12, betterproto2.TYPE_STRING)


default_message_pool.register_message("validation", "Message", Message)
