# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fixed.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66ixed.proto\x12\x05\x66ixed\":\n\x04Test\x12\x0b\n\x03\x66oo\x18\x01 \x01(\x07\x12\x0b\n\x03\x62\x61r\x18\x02 \x01(\x0f\x12\x0b\n\x03\x62\x61z\x18\x03 \x01(\x06\x12\x0b\n\x03qux\x18\x04 \x01(\x10\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fixed_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEST']._serialized_start=22
  _globals['_TEST']._serialized_end=80
# @@protoc_insertion_point(module_scope)
