# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: validation.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Message",)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Message(betterproto2.Message):
    int32_value: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT32
    )

    int64_value: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        2, betterproto2.TYPE_INT64
    )

    uint32_value: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = betterproto2.field(
        3, betterproto2.TYPE_UINT32
    )

    uint64_value: "typing.Annotated[int, pydantic.Field(ge=0, le=2**64 - 1)]" = betterproto2.field(
        4, betterproto2.TYPE_UINT64
    )

    sint32_value: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        5, betterproto2.TYPE_SINT32
    )

    sint64_value: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        6, betterproto2.TYPE_SINT64
    )

    fixed32_value: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = betterproto2.field(
        7, betterproto2.TYPE_FIXED32
    )

    fixed64_value: "typing.Annotated[int, pydantic.Field(ge=0, le=2**64 - 1)]" = betterproto2.field(
        8, betterproto2.TYPE_FIXED64
    )

    sfixed32_value: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        9, betterproto2.TYPE_SFIXED32
    )

    sfixed64_value: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        10, betterproto2.TYPE_SFIXED64
    )

    float_value: "typing.Annotated[float, pydantic.AfterValidator(betterproto2.validators.validate_float32)]" = (
        betterproto2.field(11, betterproto2.TYPE_FLOAT)
    )

    string_value: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = (
        betterproto2.field(12, betterproto2.TYPE_STRING)
    )


default_message_pool.register_message("validation", "Message", Message)
