# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: child_package_request_message.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("ChildRequestMessage",)


from typing import TYPE_CHECKING

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ChildRequestMessage(betterproto2.Message):
    child_argument: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
