# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: import_child_package_from_root.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """
    Tests generated imports when a message in root refers to a message in a child package.

    """

    child: "Optional[childpackage.Message]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


from . import childpackage
