# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: mapmessage.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Nested",
    "Test",
)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Nested(betterproto2.Message):
    count: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT32
    )


default_message_pool.register_message("mapmessage", "Nested", Nested)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    items: "dict[str, Nested]" = betterproto2.field(
        1, betterproto2.TYPE_MAP, map_meta=betterproto2.map_meta(betterproto2.TYPE_STRING, betterproto2.TYPE_MESSAGE)
    )


default_message_pool.register_message("mapmessage", "Test", Test)
