# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: mapmessage.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Nested",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    Dict,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Nested(betterproto2.Message):
    count: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    items: "Dict[str, Nested]" = betterproto2.field(
        1, betterproto2.TYPE_MAP, map_types=(betterproto2.TYPE_STRING, betterproto2.TYPE_MESSAGE)
    )
