# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: mapmessage.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Nested",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    Dict,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Nested(betterproto2.Message):
    count: "int" = betterproto2.int32_field(1)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    items: "Dict[str, Nested]" = betterproto2.map_field(1, betterproto2.TYPE_STRING, betterproto2.TYPE_MESSAGE)
