# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: google_impl_behavior_equivalence.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Empty",
    "Foo",
    "Request",
    "Spam",
    "Test",
)

import datetime
from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class Empty(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False)
class Foo(betterproto2.Message):
    bar: "int" = betterproto2.int64_field(1)


@dataclass(eq=False, repr=False)
class Request(betterproto2.Message):
    foo: "Optional[Empty]" = betterproto2.message_field(1, optional=True)


@dataclass(eq=False, repr=False)
class Spam(betterproto2.Message):
    ts: "Optional[datetime.datetime]" = betterproto2.message_field(1, optional=True)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    string: "Optional[str]" = betterproto2.string_field(1, optional=True, group="group")
    integer: "Optional[int]" = betterproto2.int64_field(2, optional=True, group="group")
    foo: "Optional[Foo]" = betterproto2.message_field(3, optional=True, group="group")
