# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: googletypes_value.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """
    Tests that fields of type google.protobuf.Value can contain arbitrary JSON-values.
    """

    value1: "_google__protobuf__.Value | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)

    value2: "_google__protobuf__.Value | None" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)

    value3: "_google__protobuf__.Value | None" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True)

    value4: "_google__protobuf__.Value | None" = betterproto2.field(4, betterproto2.TYPE_MESSAGE, optional=True)

    value5: "_google__protobuf__.Value | None" = betterproto2.field(5, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("googletypes_value", "Test", Test)


from ..google import protobuf as _google__protobuf__
