# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: googletypes_value.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """
    Tests that fields of type google.protobuf.Value can contain arbitrary JSON-values.

    """

    value1: "Optional[betterproto2_lib_google_protobuf.Value]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    value2: "Optional[betterproto2_lib_google_protobuf.Value]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )
    value3: "Optional[betterproto2_lib_google_protobuf.Value]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )
    value4: "Optional[betterproto2_lib_google_protobuf.Value]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )
    value5: "Optional[betterproto2_lib_google_protobuf.Value]" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )


import betterproto2.lib.google.protobuf as betterproto2_lib_google_protobuf
