# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nestedtwice.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "TestTopMiddleEnumBottom",
    "Test",
    "TestTop",
    "TestTopMiddle",
    "TestTopMiddleBottom",
    "TestTopMiddleTopMiddleBottom",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    List,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


class TestTopMiddleEnumBottom(betterproto2.Enum):
    """
    EnumBottom doc.
    """

    A = 0
    """
    EnumBottom.A doc. 
    """

    B = 1


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """
    Test doc.
    """

    top: "Optional[TestTop]" = betterproto2.message_field(1, optional=True)
    """
    Test.top doc. 
    """


@dataclass(eq=False, repr=False)
class TestTop(betterproto2.Message):
    """
    Top doc.
    """

    name: "str" = betterproto2.string_field(1)
    """
    Top.name doc. 
    """
    middle: "Optional[TestTopMiddle]" = betterproto2.message_field(2, optional=True)


@dataclass(eq=False, repr=False)
class TestTopMiddle(betterproto2.Message):
    """
    Middle doc.
    """

    bottom: "List[TestTopMiddleBottom]" = betterproto2.message_field(2, repeated=True)
    """
    Middle.bottom doc. 
    """
    enum_bottom: "List[TestTopMiddleEnumBottom]" = betterproto2.enum_field(
        3, repeated=True, enum_default_value=lambda: TestTopMiddleEnumBottom.try_value(0)
    )
    top_middle_bottom: "List[TestTopMiddleTopMiddleBottom]" = betterproto2.message_field(4, repeated=True)
    bar: "bool" = betterproto2.bool_field(5)


@dataclass(eq=False, repr=False)
class TestTopMiddleBottom(betterproto2.Message):
    """
    Bottom doc.
    """

    foo: "str" = betterproto2.string_field(1)
    """
    Bottom.foo doc. 
    """


@dataclass(eq=False, repr=False)
class TestTopMiddleTopMiddleBottom(betterproto2.Message):
    """
    TopMiddleBottom doc.
    """

    a: "str" = betterproto2.string_field(1)
    """
    TopMiddleBottom.a doc.
    """
