# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nestedtwice.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "TestTopMiddleEnumBottom",
    "Test",
    "TestTop",
    "TestTopMiddle",
    "TestTopMiddleBottom",
    "TestTopMiddleTopMiddleBottom",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    List,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


class TestTopMiddleEnumBottom(betterproto2.Enum):
    """
    EnumBottom doc.
    """

    A = 0
    """
    EnumBottom.A doc. 
    """

    B = 1


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """
    Test doc.

    """

    top: "Optional[TestTop]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    """
    Test.top doc. 
    """


@dataclass(eq=False, repr=False)
class TestTop(betterproto2.Message):
    """
    Top doc.

    """

    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    Top.name doc. 
    """
    middle: "Optional[TestTopMiddle]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)


@dataclass(eq=False, repr=False)
class TestTopMiddle(betterproto2.Message):
    """
    Middle doc.

    """

    bottom: "List[TestTopMiddleBottom]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, repeated=True)
    """
    Middle.bottom doc. 
    """
    enum_bottom: "List[TestTopMiddleEnumBottom]" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, repeated=True, default_factory=lambda: TestTopMiddleEnumBottom.try_value(0)
    )
    top_middle_bottom: "List[TestTopMiddleTopMiddleBottom]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )
    bar: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class TestTopMiddleBottom(betterproto2.Message):
    """
    Bottom doc.

    """

    foo: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    Bottom.foo doc. 
    """


@dataclass(eq=False, repr=False)
class TestTopMiddleTopMiddleBottom(betterproto2.Message):
    """
    TopMiddleBottom doc.

    """

    a: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    TopMiddleBottom.a doc.
    """
