# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: features.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Bar",
    "Empty",
    "Enum",
    "EnumMsg",
    "Foo",
    "IntMsg",
    "JsonCasingMsg",
    "MsgA",
    "MsgB",
    "MsgC",
    "MsgD",
    "MsgE",
    "Newer",
    "Older",
    "OneofMsg",
    "OptionalBoolMsg",
    "OptionalDatetimeMsg",
    "TimeMsg",
)

import datetime
import typing

import betterproto2
import pydantic
from pydantic import model_validator
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


class Enum(betterproto2.Enum):
    ZERO = 0

    ONE = 1

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Bar(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = (
        betterproto2.field(1, betterproto2.TYPE_STRING)
    )


default_message_pool.register_message("features", "Bar", Bar)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Empty(betterproto2.Message):
    pass


default_message_pool.register_message("features", "Empty", Empty)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class EnumMsg(betterproto2.Message):
    enum: "Enum" = betterproto2.field(1, betterproto2.TYPE_ENUM, default_factory=lambda: Enum(0))


default_message_pool.register_message("features", "EnumMsg", EnumMsg)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Foo(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = (
        betterproto2.field(1, betterproto2.TYPE_STRING)
    )

    child: "Bar | None" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("features", "Foo", Foo)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class IntMsg(betterproto2.Message):
    val: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT32
    )


default_message_pool.register_message("features", "IntMsg", IntMsg)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class JsonCasingMsg(betterproto2.Message):
    pascal_case: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT32
    )

    camel_case: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        2, betterproto2.TYPE_INT32
    )

    snake_case: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        3, betterproto2.TYPE_INT32
    )

    kabob_case: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        4, betterproto2.TYPE_INT32
    )


default_message_pool.register_message("features", "JsonCasingMsg", JsonCasingMsg)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MsgA(betterproto2.Message):
    some_int: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT32
    )

    some_double: "float" = betterproto2.field(2, betterproto2.TYPE_DOUBLE)

    some_str: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = (
        betterproto2.field(3, betterproto2.TYPE_STRING)
    )

    some_bool: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)


default_message_pool.register_message("features", "MsgA", MsgA)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MsgB(betterproto2.Message):
    some_int: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT32
    )

    some_double: "float" = betterproto2.field(2, betterproto2.TYPE_DOUBLE)

    some_str: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = (
        betterproto2.field(3, betterproto2.TYPE_STRING)
    )

    some_bool: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)

    some_default_int: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        5, betterproto2.TYPE_INT32
    )

    some_default_double: "float" = betterproto2.field(6, betterproto2.TYPE_DOUBLE)

    some_default_str: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = (
        betterproto2.field(7, betterproto2.TYPE_STRING)
    )

    some_default_bool: "bool" = betterproto2.field(8, betterproto2.TYPE_BOOL)


default_message_pool.register_message("features", "MsgB", MsgB)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MsgC(betterproto2.Message):
    """


    Oneofs:
        - group1:
    """

    int_field: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)] | None" = betterproto2.field(
        1, betterproto2.TYPE_INT32, optional=True, group="group1"
    )

    string_field: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)] | None" = (
        betterproto2.field(2, betterproto2.TYPE_STRING, optional=True, group="group1")
    )

    empty_field: "Empty | None" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True, group="group1")

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


default_message_pool.register_message("features", "MsgC", MsgC)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MsgD(betterproto2.Message):
    timestamps: "list[datetime.datetime]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.Timestamp, repeated=True
    )


default_message_pool.register_message("features", "MsgD", MsgD)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MsgE(betterproto2.Message):
    bool_field: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    int_field: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)] | None" = betterproto2.field(
        2, betterproto2.TYPE_INT32, optional=True
    )


default_message_pool.register_message("features", "MsgE", MsgE)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Newer(betterproto2.Message):
    x: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    y: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(2, betterproto2.TYPE_INT32)

    z: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("features", "Newer", Newer)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Older(betterproto2.Message):
    x: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)


default_message_pool.register_message("features", "Older", Older)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class OneofMsg(betterproto2.Message):
    """


    Oneofs:
        - group1:
        - group2:
    """

    x: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)] | None" = betterproto2.field(
        1, betterproto2.TYPE_INT32, optional=True, group="group1"
    )

    y: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)] | None" = (
        betterproto2.field(2, betterproto2.TYPE_STRING, optional=True, group="group1")
    )

    a: "IntMsg | None" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True, group="group2")

    b: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)] | None" = (
        betterproto2.field(4, betterproto2.TYPE_STRING, optional=True, group="group2")
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


default_message_pool.register_message("features", "OneofMsg", OneofMsg)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class OptionalBoolMsg(betterproto2.Message):
    field: "bool | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.BoolValue, optional=True
    )


default_message_pool.register_message("features", "OptionalBoolMsg", OptionalBoolMsg)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class OptionalDatetimeMsg(betterproto2.Message):
    field: "datetime.datetime | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.Timestamp, optional=True
    )


default_message_pool.register_message("features", "OptionalDatetimeMsg", OptionalDatetimeMsg)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TimeMsg(betterproto2.Message):
    timestamp: "datetime.datetime | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.Timestamp, optional=True
    )

    duration: "datetime.timedelta | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.Duration, optional=True
    )


default_message_pool.register_message("features", "TimeMsg", TimeMsg)


from ..google import protobuf as _google__protobuf__
