# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: features.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Enum",
    "Bar",
    "Empty",
    "EnumMsg",
    "Foo",
    "IntMsg",
    "JsonCasingMsg",
    "MsgA",
    "MsgB",
    "MsgC",
    "MsgD",
    "MsgE",
    "Newer",
    "Older",
    "OneofMsg",
    "OptionalBoolMsg",
    "OptionalDatetimeMsg",
    "TimeMsg",
)

import datetime
from typing import (
    TYPE_CHECKING,
    List,
    Optional,
)

import betterproto2
from pydantic import model_validator
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


class Enum(betterproto2.Enum):
    ZERO = 0

    ONE = 1

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Bar(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Empty(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class EnumMsg(betterproto2.Message):
    enum: "Enum" = betterproto2.field(1, betterproto2.TYPE_ENUM, default_factory=lambda: Enum.try_value(0))


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Foo(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    child: "Optional[Bar]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class IntMsg(betterproto2.Message):
    val: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class JsonCasingMsg(betterproto2.Message):
    pascal_case: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    camel_case: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
    snake_case: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)
    kabob_case: "int" = betterproto2.field(4, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MsgA(betterproto2.Message):
    some_int: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    some_double: "float" = betterproto2.field(2, betterproto2.TYPE_DOUBLE)
    some_str: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    some_bool: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MsgB(betterproto2.Message):
    some_int: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    some_double: "float" = betterproto2.field(2, betterproto2.TYPE_DOUBLE)
    some_str: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    some_bool: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)
    some_default_int: "int" = betterproto2.field(5, betterproto2.TYPE_INT32)
    some_default_double: "float" = betterproto2.field(6, betterproto2.TYPE_DOUBLE)
    some_default_str: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    some_default_bool: "bool" = betterproto2.field(8, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MsgC(betterproto2.Message):
    """


    Oneofs:
        - group1:
    """

    int_field: "Optional[int]" = betterproto2.field(1, betterproto2.TYPE_INT32, optional=True, group="group1")
    string_field: "Optional[str]" = betterproto2.field(2, betterproto2.TYPE_STRING, optional=True, group="group1")
    empty_field: "Optional[Empty]" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True, group="group1")

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MsgD(betterproto2.Message):
    timestamps: "List[datetime.datetime]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, repeated=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class MsgE(betterproto2.Message):
    """


    Oneofs:
        - _int_field:
    """

    bool_field: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    int_field: "Optional[int]" = betterproto2.field(2, betterproto2.TYPE_INT32, optional=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Newer(betterproto2.Message):
    x: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    y: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
    z: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Older(betterproto2.Message):
    x: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class OneofMsg(betterproto2.Message):
    """


    Oneofs:
        - group1:
        - group2:
    """

    x: "Optional[int]" = betterproto2.field(1, betterproto2.TYPE_INT32, optional=True, group="group1")
    y: "Optional[str]" = betterproto2.field(2, betterproto2.TYPE_STRING, optional=True, group="group1")
    a: "Optional[IntMsg]" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True, group="group2")
    b: "Optional[str]" = betterproto2.field(4, betterproto2.TYPE_STRING, optional=True, group="group2")

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class OptionalBoolMsg(betterproto2.Message):
    field: "Optional[Optional[bool]]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, wraps=betterproto2.TYPE_BOOL, optional=True
    )


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class OptionalDatetimeMsg(betterproto2.Message):
    field: "Optional[datetime.datetime]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TimeMsg(betterproto2.Message):
    timestamp: "Optional[datetime.datetime]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    duration: "Optional[datetime.timedelta]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)
