# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unwrap.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cunwrap.proto\x12\x06unwrap\"\x1a\n\rNestedMessage\x12\t\n\x01x\x18\x01 \x01(\x05\"+\n\x07Message\x12 \n\x01x\x18\x01 \x01(\x0b\x32\x15.unwrap.NestedMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unwrap_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NESTEDMESSAGE']._serialized_start=24
  _globals['_NESTEDMESSAGE']._serialized_end=50
  _globals['_MESSAGE']._serialized_start=52
  _globals['_MESSAGE']._serialized_end=95
# @@protoc_insertion_point(module_scope)
