# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: signed.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    signed32: "int" = betterproto2.field(1, betterproto2.TYPE_SINT32)
    """
    todo: rename fields after fixing bug where 'signed_32_positive' will map to 'signed_32Positive' as output json

     signed_32_positive
    """

    negative32: "int" = betterproto2.field(2, betterproto2.TYPE_SINT32)
    """
     signed_32_negative
    """

    string64: "int" = betterproto2.field(3, betterproto2.TYPE_SINT64)
    """
     signed_64_positive
    """

    negative64: "int" = betterproto2.field(4, betterproto2.TYPE_SINT64)
    """
     signed_64_negative
    """


default_message_pool.register_message("signed", "Test", Test)
