# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: import_packages_same_name.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import users_v1_pb2 as users__v1__pb2
import posts_v1_pb2 as posts__v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fimport_packages_same_name.proto\x12\x19import_packages_same_name\x1a\x0eusers_v1.proto\x1a\x0eposts_v1.proto\"v\n\x04Test\x12\x36\n\x04user\x18\x01 \x01(\x0b\x32(.import_packages_same_name.users.v1.User\x12\x36\n\x04post\x18\x02 \x01(\x0b\x32(.import_packages_same_name.posts.v1.Postb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'import_packages_same_name_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEST']._serialized_start=94
  _globals['_TEST']._serialized_end=212
# @@protoc_insertion_point(module_scope)
