# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: test.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """
    Verify that we can import message unrelated to us
    """

    message: "Optional[__cousin_cousin_subpackage__.CousinMessage]" = betterproto2.message_field(1, optional=True)


from ...cousin import cousin_subpackage as __cousin_cousin_subpackage__
