# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: enum.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "ArithmeticOperator",
    "Choice",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    List,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


class ArithmeticOperator(betterproto2.Enum):
    """
    A "C" like enum with the enum name prefixed onto members, these should be stripped
    """

    NONE = 0

    PLUS = 1

    MINUS = 2

    _0_PREFIXED = 3

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


class Choice(betterproto2.Enum):
    ZERO = 0

    ONE = 1

    FOUR = 4
    """
    TWO = 2;
    """

    THREE = 3

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """
    Tests that enums are correctly serialized and that it correctly handles skipped and out-of-order enum values
    """

    choice: "Choice" = betterproto2.enum_field(1, enum_default_value=lambda: Choice.try_value(0))
    choices: "List[Choice]" = betterproto2.enum_field(2, repeated=True, enum_default_value=lambda: Choice.try_value(0))
