# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ref.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import repeatedmessage_pb2 as repeatedmessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tref.proto\x12\x03ref\x1a\x15repeatedmessage.proto\".\n\x04Test\x12&\n\x08greeting\x18\x01 \x01(\x0b\x32\x14.repeatedmessage.Subb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ref_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEST']._serialized_start=41
  _globals['_TEST']._serialized_end=87
# @@protoc_insertion_point(module_scope)
