# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: import_packages_same_name.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """
    Tests generated message can correctly reference two packages with the same leaf-name

    """

    user: "Optional[users_v1.User]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    post: "Optional[posts_v1.Post]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)


from .posts import v1 as posts_v1
from .users import v1 as users_v1
