# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: casing.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "MyEnum",
    "SnakeCaseMessage",
    "Test",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


class MyEnum(betterproto2.Enum):
    ZERO = 0

    ONE = 1

    TWO = 2


@dataclass(eq=False, repr=False)
class SnakeCaseMessage(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    camel_case: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    snake_case: "MyEnum" = betterproto2.field(2, betterproto2.TYPE_ENUM, default_factory=lambda: MyEnum.try_value(0))
    snake_case_message: "Optional[SnakeCaseMessage]" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True)
    uppercase: "int" = betterproto2.field(4, betterproto2.TYPE_INT32)
