# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: casing.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "MyEnum",
    "SnakeCaseMessage",
    "Test",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


class MyEnum(betterproto2.Enum):
    ZERO = 0

    ONE = 1

    TWO = 2


@dataclass(eq=False, repr=False)
class SnakeCaseMessage(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    camel_case: "int" = betterproto2.int32_field(1)
    snake_case: "MyEnum" = betterproto2.enum_field(2, enum_default_value=lambda: MyEnum.try_value(0))
    snake_case_message: "Optional[SnakeCaseMessage]" = betterproto2.message_field(3, optional=True)
    uppercase: "int" = betterproto2.int32_field(4)
