# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: oneof_enum.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Signal",
    "Move",
    "Test",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


class Signal(betterproto2.Enum):
    PASS = 0

    RESIGN = 1


@dataclass(eq=False, repr=False)
class Move(betterproto2.Message):
    x: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    y: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """


    Oneofs:
        - action:
    """

    signal: "Optional[Signal]" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, optional=True, default_factory=lambda: Signal.try_value(0), group="action"
    )
    move: "Optional[Move]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True, group="action")
