# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: import_parent_package_from_child.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


import betterproto2
from pydantic.dataclasses import dataclass

from ....message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """
    Tests generated imports when a message refers to a message defined in its parent package
    """

    message_implicit: "__parent__.ParentPackageMessage | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    message_explicit: "__parent__.ParentPackageMessage | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("import_parent_package_from_child.parent.child", "Test", Test)


from ... import parent as __parent__
