# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: signed.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from typing import TYPE_CHECKING

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    signed32: "int" = betterproto2.sint32_field(1)
    """
    todo: rename fields after fixing bug where 'signed_32_positive' will map to 'signed_32Positive' as output json

     signed_32_positive
    """
    negative32: "int" = betterproto2.sint32_field(2)
    """
     signed_32_negative
    """
    string64: "int" = betterproto2.sint64_field(3)
    """
     signed_64_positive
    """
    negative64: "int" = betterproto2.sint64_field(4)
    """
     signed_64_negative
    """
