# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: bool.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


import betterproto2
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    value: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)


default_message_pool.register_message("bool", "Test", Test)
