# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: import_circular_dependency.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import root_pb2 as root__pb2
import other_pb2 as other__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n import_circular_dependency.proto\x12\x1aimport_circular_dependency\x1a\nroot.proto\x1a\x0bother.proto\"\x93\x01\n\x04Test\x12?\n\x07message\x18\x01 \x01(\x0b\x32..import_circular_dependency.RootPackageMessage\x12J\n\x0bother_value\x18\x02 \x01(\x0b\x32\x35.import_circular_dependency.other.OtherPackageMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'import_circular_dependency_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEST']._serialized_start=90
  _globals['_TEST']._serialized_end=237
# @@protoc_insertion_point(module_scope)
