# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: field_name_identical_to_type.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

import builtins
from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """
    Tests that messages may contain fields with names that are identical to their python types (PR #294)
    """

    int: "builtins.int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    float: "builtins.float" = betterproto2.field(2, betterproto2.TYPE_FLOAT)

    str: "builtins.str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    bytes: "builtins.bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)

    bool: "builtins.bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)


default_message_pool.register_message("field_name_identical_to_type", "Test", Test)
