# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: regression_387.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "ParentElement",
    "Test",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    List,
)

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class ParentElement(betterproto2.Message):
    name: "str" = betterproto2.string_field(1)
    elems: "List[Test]" = betterproto2.message_field(2, repeated=True)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    id: "int" = betterproto2.uint64_field(1)
