# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: other.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("OtherPackageMessage",)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class OtherPackageMessage(betterproto2.Message):
    root_package_message: "Optional[__import_circular_dependency__.RootPackageMessage]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


from ... import import_circular_dependency as __import_circular_dependency__
