# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: double.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    count: "float" = betterproto2.field(1, betterproto2.TYPE_DOUBLE)
