# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nested2.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Game", "GamePlayer", "GamePlayerRace", "Test")

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


class GamePlayerRace(betterproto2.Enum):
    human = 0

    orc = 1


@dataclass(eq=False, repr=False)
class Game(betterproto2.Message):
    pass


default_message_pool.register_message("nested2", "Game", Game)


@dataclass(eq=False, repr=False)
class GamePlayer(betterproto2.Message):
    pass


default_message_pool.register_message("nested2", "Game.Player", GamePlayer)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    game: "Game | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)

    game_player: "GamePlayer | None" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)

    game_player_race: "GamePlayerRace" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: GamePlayerRace(0)
    )

    weapon: "equipment.Weapon | None" = betterproto2.field(4, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("nested2", "Test", Test)


from . import equipment
