# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nested2.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "GamePlayerRace",
    "Game",
    "GamePlayer",
    "Test",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


class GamePlayerRace(betterproto2.Enum):
    human = 0

    orc = 1


@dataclass(eq=False, repr=False)
class Game(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False)
class GamePlayer(betterproto2.Message):
    pass


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    game: "Optional[Game]" = betterproto2.message_field(1, optional=True)
    game_player: "Optional[GamePlayer]" = betterproto2.message_field(2, optional=True)
    game_player_race: "GamePlayerRace" = betterproto2.enum_field(
        3, enum_default_value=lambda: GamePlayerRace.try_value(0)
    )
    weapon: "Optional[equipment.Weapon]" = betterproto2.message_field(4, optional=True)


from . import equipment
