# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: parent_package_message.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("ParentPackageMessage",)


import betterproto2
from pydantic.dataclasses import dataclass

from ...message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ParentPackageMessage(betterproto2.Message):
    pass


default_message_pool.register_message(
    "import_parent_package_from_child.parent", "ParentPackageMessage", ParentPackageMessage
)
