# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: timestamp_dict_encode.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

import datetime

import betterproto2
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    ts: "datetime.datetime | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, unwrap=lambda: _google__protobuf__.Timestamp, optional=True
    )


default_message_pool.register_message("timestamp_dict_encode", "Test", Test)


from ..google import protobuf as _google__protobuf__
