# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: import_nested_child_package_from_root.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    child: "Optional[package_child_otherchild.ChildMessage]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


from .package.child import otherchild as package_child_otherchild
