# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signed.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csigned.proto\x12\x06signed\"R\n\x04Test\x12\x10\n\x08signed32\x18\x01 \x01(\x11\x12\x12\n\nnegative32\x18\x02 \x01(\x11\x12\x10\n\x08string64\x18\x03 \x01(\x12\x12\x12\n\nnegative64\x18\x04 \x01(\x12\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signed_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEST']._serialized_start=24
  _globals['_TEST']._serialized_end=106
# @@protoc_insertion_point(module_scope)
