# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: package_message.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("PackageMessage",)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class PackageMessage(betterproto2.Message):
    c: "Optional[childpackage.ChildMessage]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


from . import childpackage
