# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: recursivemessage.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Intermediate",
    "Test",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class Intermediate(betterproto2.Message):
    number: "int" = betterproto2.int32_field(1)
    child: "Optional[Test]" = betterproto2.message_field(2, optional=True)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    name: "str" = betterproto2.string_field(1)
    child: "Optional[Test]" = betterproto2.message_field(2, optional=True)
    intermediate: "Optional[Intermediate]" = betterproto2.message_field(3, optional=True)
