# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: recursivemessage.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Intermediate",
    "Test",
)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False)
class Intermediate(betterproto2.Message):
    number: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    child: "Optional[Test]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    child: "Optional[Test]" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)
    intermediate: "Optional[Intermediate]" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True)
