# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: googletypes_value.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    """
    Tests that fields of type google.protobuf.Value can contain arbitrary JSON-values.
    """

    value1: "Optional[betterproto2_lib_pydantic_google_protobuf.Value]" = betterproto2.message_field(1, optional=True)
    value2: "Optional[betterproto2_lib_pydantic_google_protobuf.Value]" = betterproto2.message_field(2, optional=True)
    value3: "Optional[betterproto2_lib_pydantic_google_protobuf.Value]" = betterproto2.message_field(3, optional=True)
    value4: "Optional[betterproto2_lib_pydantic_google_protobuf.Value]" = betterproto2.message_field(4, optional=True)
    value5: "Optional[betterproto2_lib_pydantic_google_protobuf.Value]" = betterproto2.message_field(5, optional=True)


import betterproto2.lib.pydantic.google.protobuf as betterproto2_lib_pydantic_google_protobuf
