# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: stream_stream.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Message",)


import betterproto2
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.3.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Message(betterproto2.Message):
    body: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("stream_stream", "Message", Message)
