# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: test.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    """
    Tests that we can import from a package with a capital name, that looks like a nested type, but isn't.
    """

    message: "Optional[Capitalized.Message]" = betterproto2.message_field(1, optional=True)


from . import Capitalized
