# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: googletypes_service_returns_empty.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "RequestMessage",
    "TestStub",
    "TestBase",
)


from typing import (
    TYPE_CHECKING,
    Dict,
    Optional,
)

import betterproto2
import grpclib
from betterproto2.grpc.grpclib_server import ServiceBase
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    import grpclib.server
    from betterproto2.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class RequestMessage(betterproto2.Message):
    pass


class TestStub(betterproto2.ServiceStub):
    async def send(
        self,
        request_message: "RequestMessage | None" = None,
        *,
        timeout: Optional[float] = None,
        deadline: "Optional[Deadline]" = None,
        metadata: "Optional[MetadataLike]" = None,
    ) -> "betterproto2_lib_pydantic_google_protobuf.Empty":
        if request_message is None:
            request_message = RequestMessage()

        return await self._unary_unary(
            "/googletypes_service_returns_empty.Test/Send",
            request_message,
            betterproto2_lib_pydantic_google_protobuf.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


import betterproto2.lib.pydantic.google.protobuf as betterproto2_lib_pydantic_google_protobuf


class TestBase(ServiceBase):
    async def send(self, request_message: "RequestMessage") -> "betterproto2_lib_pydantic_google_protobuf.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_send(
        self, stream: "grpclib.server.Stream[RequestMessage, betterproto2_lib_pydantic_google_protobuf.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.send(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/googletypes_service_returns_empty.Test/Send": grpclib.const.Handler(
                self.__rpc_send,
                grpclib.const.Cardinality.UNARY_UNARY,
                RequestMessage,
                betterproto2_lib_pydantic_google_protobuf.Empty,
            ),
        }
