# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: users_v1.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("User",)


from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class User(betterproto2.Message):
    pass
