# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmap.proto\x12\x03map\"\\\n\x04Test\x12%\n\x06\x63ounts\x18\x01 \x03(\x0b\x32\x15.map.Test.CountsEntry\x1a-\n\x0b\x43ountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEST_COUNTSENTRY']._options = None
  _globals['_TEST_COUNTSENTRY']._serialized_options = b'8\001'
  _globals['_TEST']._serialized_start=18
  _globals['_TEST']._serialized_end=110
  _globals['_TEST_COUNTSENTRY']._serialized_start=65
  _globals['_TEST_COUNTSENTRY']._serialized_end=110
# @@protoc_insertion_point(module_scope)
