# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: unwrap.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Message",
    "NestedMessage",
)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class Message(betterproto2.Message):
    x: "NestedMessage | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("unwrap", "Message", Message)


@dataclass(eq=False, repr=False)
class NestedMessage(betterproto2.Message):
    x: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)


default_message_pool.register_message("unwrap", "NestedMessage", NestedMessage)
