# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: repeatedpacked.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    counts: "list[int]" = betterproto2.field(1, betterproto2.TYPE_INT32, repeated=True)

    signed: "list[int]" = betterproto2.field(2, betterproto2.TYPE_SINT64, repeated=True)

    fixed: "list[float]" = betterproto2.field(3, betterproto2.TYPE_DOUBLE, repeated=True)


default_message_pool.register_message("repeatedpacked", "Test", Test)
