# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: pickling.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Complex",
    "Fe",
    "Fi",
    "Fo",
    "NestedData",
    "PickledMessage",
    "Test",
)


from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto2
from pydantic import model_validator
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass

betterproto2.check_compiler_version("0.1.0")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Complex(betterproto2.Message):
    """


    Oneofs:
        - grp:
    """

    foo_str: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    fe: "Optional[Fe]" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True, group="grp")
    fi: "Optional[Fi]" = betterproto2.field(4, betterproto2.TYPE_MESSAGE, optional=True, group="grp")
    fo: "Optional[Fo]" = betterproto2.field(5, betterproto2.TYPE_MESSAGE, optional=True, group="grp")
    nested_data: "Optional[NestedData]" = betterproto2.field(6, betterproto2.TYPE_MESSAGE, optional=True)
    mapping: "Dict[str, betterproto2_lib_pydantic_google_protobuf.Any]" = betterproto2.field(
        7, betterproto2.TYPE_MAP, map_types=(betterproto2.TYPE_STRING, betterproto2.TYPE_MESSAGE)
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Fe(betterproto2.Message):
    abc: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Fi(betterproto2.Message):
    abc: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Fo(betterproto2.Message):
    abc: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class NestedData(betterproto2.Message):
    struct_foo: "Dict[str, betterproto2_lib_pydantic_google_protobuf.Struct]" = betterproto2.field(
        1, betterproto2.TYPE_MAP, map_types=(betterproto2.TYPE_STRING, betterproto2.TYPE_MESSAGE)
    )
    map_str_any_bar: "Dict[str, betterproto2_lib_pydantic_google_protobuf.Any]" = betterproto2.field(
        2, betterproto2.TYPE_MAP, map_types=(betterproto2.TYPE_STRING, betterproto2.TYPE_MESSAGE)
    )


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class PickledMessage(betterproto2.Message):
    foo: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    bar: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
    baz: "List[str]" = betterproto2.field(3, betterproto2.TYPE_STRING, repeated=True)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    pass


import betterproto2.lib.pydantic.google.protobuf as betterproto2_lib_pydantic_google_protobuf
