# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: repeatedmessage.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15repeatedmessage.proto\x12\x0frepeatedmessage\"/\n\x04Test\x12\'\n\tgreetings\x18\x01 \x03(\x0b\x32\x14.repeatedmessage.Sub\"\x17\n\x03Sub\x12\x10\n\x08greeting\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'repeatedmessage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEST']._serialized_start=42
  _globals['_TEST']._serialized_end=89
  _globals['_SUB']._serialized_start=91
  _globals['_SUB']._serialized_end=114
# @@protoc_insertion_point(module_scope)
