# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: repeated.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    List,
)

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    names: "List[str]" = betterproto2.string_field(1, repeated=True)
