# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: bytes.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from typing import TYPE_CHECKING

import betterproto2
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto2.Message):
    data: "bytes" = betterproto2.bytes_field(1)
