# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: unwrap.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Message",
    "NestedMessage",
)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

betterproto2.check_compiler_version("0.5.1")


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Message(betterproto2.Message):
    x: "NestedMessage | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)


default_message_pool.register_message("unwrap", "Message", Message)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class NestedMessage(betterproto2.Message):
    x: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(1, betterproto2.TYPE_INT32)


default_message_pool.register_message("unwrap", "NestedMessage", NestedMessage)
