name: Release

on:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  packaging:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    name: Distribution
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/betterproto2_compiler

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install poetry
        run: python -m pip install poetry

      - name: Build package
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.12
