# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: googletypes_struct.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Optional,
)

import betterproto2

if TYPE_CHECKING:
    pass


@dataclass(eq=False, repr=False)
class Test(betterproto2.Message):
    struct: "Optional[betterproto2_lib_google_protobuf.Struct]" = betterproto2.message_field(1, optional=True)


import betterproto2.lib.google.protobuf as betterproto2_lib_google_protobuf
